--[[
Note: please use UTF-8 characters to encode, edit, and save this file

Fast index for translation area
简体中文: zhCN
한국어     : koKR
正體中文: zhTW
English	: enUS as default

Currently default with zhTW, if no translation keyword matches
]]

if (GetLocale() == "zhCN") then

EUF_TEXT_OPTION_HEADER                        ="EUF头像增强参数设定";
EUF_TEXT_OPTION_ENABLE                        ="启用Enigma Unit Frames";
EUF_TEXT_OPTION_PLAYERFRM                     ="显示头像边框";
EUF_TEXT_OPTION_PLAYERHP                      ="显示玩家生命值";
EUF_TEXT_OPTION_PLAYERMP                      ="显示玩家魔法值";
EUF_TEXT_OPTION_PLAYERXP                      ="显示玩家经验值条";
EUF_TEXT_OPTION_PLAYERXPAUTO                  ="满级自动隐藏经验值条";
EUF_TEXT_OPTION_PLAYERPOSITION                ="显示玩家坐标";
EUF_TEXT_OPTION_PLAYERPOSITIONTOHP            ="将坐标替换为生命值百分比";
EUF_TEXT_OPTION_PLAYERPETHPMP                 ="显示宠物的HP和MP"
EUF_TEXT_OPTION_PLAYERPOSITIONAUTOHP          ="在副本里显示生命值百分比";
EUF_TEXT_OPTION_PLAYERAUTOHEALTHCOLOR         ="自动调节生命条颜色";
EUF_TEXT_OPTION_PLAYEREXTBAR                  ="显示扩展边框";
EUF_TEXT_OPTION_PLAYERCLASSICONBIG            ="显示玩家职业图标(大)";
EUF_TEXT_OPTION_PLAYERCLASSICONSMALL          ="显示玩家职业图标(小)";
EUF_TEXT_OPTION_PLAYER3DPORTRAIT              ="显示玩家3D头像";

EUF_TEXT_OPTION_PARTYHP                       ="显示队友生命值";
EUF_TEXT_OPTION_PARTYMP                       ="显示队友魔法值";
EUF_TEXT_OPTION_PARTYAUTOHEALTHCOLOR          ="自动调节生命条颜色";
EUF_TEXT_OPTION_PARTYLEVEL                    ="显示队友等级";
EUF_TEXT_OPTION_PARTYCLASS                    ="显示队友职业名称";
EUF_TEXT_OPTION_PARTYCLASSABRV                ="以缩写方式显示职业名称";
EUF_TEXT_OPTION_PARTYCOLOR                    ="队友名字按职业着色";
EUF_TEXT_OPTION_PARTYMANAFILTER               ="无魔法的职业不显示魔法值";
EUF_TEXT_OPTION_PARTYCLASSICONBIG             ="显示队友职业图标(大)";
EUF_TEXT_OPTION_PARTYCLASSICONSMALL           ="显示队友职业图标(小)";
EUF_TEXT_OPTION_PARTY3DPORTRAIT               ="显示队友3D头像";
EUF_TEXT_OPTION_PARTYHIDE                     ="隐藏队伍框架";
EUF_TEXT_OPTION_PARTYCAST                     ="显示队友施法条";
EUF_TEXT_OPTION_PARTYBUFF                     ="显示队友BUFF";
EUF_TEXT_OPTION_PARTYTARGET                   ="显示队友目标";

EUF_TEXT_OPTION_TARGETHP                      ="显示目标生命值";
EUF_TEXT_OPTION_TARGETMP                      ="显示目标魔法值";
EUF_TEXT_OPTION_TARGETHPPERCENT               ="显示目标生命值百分比";
EUF_TEXT_OPTION_TARGETMPPERCENT               ="显示目标魔法值百分比";
EUF_TEXT_OPTION_TARGETAUTOHEALTHCOLOR         ="自动调节生命条颜色";
EUF_TEXT_OPTION_TARGETPERCENTINSIDE           ="将百分比显示在血条内";
EUF_TEXT_OPTION_TARGETOTWARNING               ="仇恨报警";
EUF_TEXT_OPTION_TARGETINFO                    ="显示目标信息";
EUF_TEXT_OPTION_TARGETINFOLEVEL               ="级别";
EUF_TEXT_OPTION_TARGETINFORACE                ="种族";
EUF_TEXT_OPTION_TARGETINFOCLASS               ="职业";
EUF_TEXT_OPTION_TARGETINFOELITE               ="精英类型";
EUF_TEXT_OPTION_TARGETINFOTARGET              ="显示目标的目标(简略)";
EUF_TEXT_OPTION_TARGETINFOBROKENSHIELD        ="显示目标破甲值";
EUF_TEXT_OPTION_TARGETTARGETHPMPBAR           ="显示目标的目标生命值/魔法值条";
EUF_TEXT_OPTION_TARGETTARGETHPPERCENT         ="显示目标的目标生命值百分比";
EUF_TEXT_OPTION_TARGETTARGETHPPERCENTCOLOR    ="自动调整生命条颜色";
EUF_TEXT_OPTION_TARGETCLASSICONBIG            ="显示目标职业图标(大)";
EUF_TEXT_OPTION_TARGETCLASSICONSMALL          ="显示目标职业图标(小)";
EUF_TEXT_OPTION_TARGETTARGETFRAME             ="显示目标的目标(标准)";
EUF_TEXT_OPTION_TARGETTARGETTARGETFRAME       ="显示目标的目标的目标(标准)";
EUF_TEXT_OPTION_MOVINGTARGETTARGETFRAME       ="移动目标的目标(标准)";
EUF_TEXT_OPTION_TARGET3DPORTRAIT              ="显示目标3D头像";
EUF_TEXT_OPTION_TARGETINDICATOR               ="目标头像显示战斗数值";

EUF_TEXT_OPTION_FOCUSHP                       ="显示焦点生命值";
EUF_TEXT_OPTION_FOCUSHPPERCENT                ="显示焦点生命值百分比";
EUF_TEXT_OPTION_FOCUSPERCENTINSIDE            ="将百分比显示在血条内";
EUF_TEXT_OPTION_FOCUS3DPORTRAIT               ="显示焦点3D头像";
EUF_TEXT_OPTION_FOCUSCLASSICONBIG             ="显示焦点职业图标(大)";
EUF_TEXT_OPTION_FOCUSCLASSICONSMALL           ="显示焦点职业图标(小)";

EUF_TEXT_OPTION_NOTINSTALLED                  ="参数设定模块未安装,无法启动窗口设定模式.";
EUF_TEXT_OPTION_HELP1                         ="请使用命令行模式设定,用法如下:";
EUF_TEXT_OPTION_HELP2                         ="/euf 选项 参数(示例: /euf PlayerHp 0)";
EUF_TEXT_OPTION_HELP3                         ="具体选项请参考readme.txt,参数为0/1或on/off";
EUF_TEXT_OPTION_SET                           ="已将参数[%s] 设定为 %s";
EUF_TEXT_OPTION_INVALIDPARAM                  ="无效参数";
EUF_TEXT_OPTION_NOTCOMPATIBLE                 ="以前的参数设置与新版本的参数设置不兼容,以前的参数设置将被清除,请重新设定.";

EUF_TEXT_OPTION_DISPLAYTYPE                   ="显示方式";
EUF_TEXT_OPTION_NUM                           ="数字";
EUF_TEXT_OPTION_PERCENT                       ="百分比";
EUF_TEXT_OPTION_ELITE                         ="精英";
EUF_TEXT_OPTION_RARE                          ="稀有";
EUF_TEXT_OPTION_PLAYER                        ="玩家信息";
EUF_TEXT_OPTION_PARTY                         ="队伍信息";
EUF_TEXT_OPTION_TARGET                        ="目标信息";
EUF_TEXT_OPTION_TARGETTARGET                  ="目标的目标";
EUF_TEXT_OPTION_FOCUS                         ="焦点目标";
EUF_TEXT_DEFAULTOPTIONS                       ="默认设置";
EUF_TEXT_CONFIRM                              ="确定";
EUF_TEXT_RESETPOSITION                        ="默认头像位置"
EUF_TEXT_PARTYBUFFPOSITION                    ="调整队友Buff位置"
EUF_TEXT_PARTYDEBUFFPOSITION                  ="调整队友Debuff位置"
EUF_TEXT_PARTYTARGETPOSITION                  ="调整队友目标位置"
EUF_TEXT_PARTYCASTPOSITION                    ="调整队友施法条位置"
EUF_TEXT_TARGET                               ="目标 ";
EUF_TEXT_BROKENSHIELD                         ="破甲 ";
EUF_TEXT_LEVELTAG                             ="%s级";
EUF_TEXT_10KTAG                               ="%s万";
EUF_TEXT_ELITE                                ="精英";
EUF_TEXT_WORLDBOSS                            ="世界精英";
EUF_TEXT_RARE                                 ="稀有";
EUF_TEXT_RAREELITE                            ="稀有精英";

EUF_FOCUSFRAME_DRAG                           ="点击拖移框架以移动";
EUF_FOCUSFRAME_DRAG_LOCKED                    ="请先使用/focusframe unlock解除框架锁定";

elseif (GetLocale() == "koKR") then

EUF_FOCUSFRAME_DRAG = "드래그로 이동";
EUF_FOCUSFRAME_DRAG_LOCKED = "/focusframe 명령으로 이동시킬 수 있습니다.";
EUF_TEXT_10KTAG = "%s백만";
EUF_TEXT_BROKENSHIELD = "방어구 가르기 ";
EUF_TEXT_CONFIRM = "확인";
EUF_TEXT_DEFAULTOPTIONS = "기본값";
EUF_TEXT_ELITE = "정예";
EUF_TEXT_LEVELTAG = "%s레벨";
EUF_TEXT_OPTION_DISPLAYTYPE = "표시 형식";
EUF_TEXT_OPTION_ELITE = "정예";
EUF_TEXT_OPTION_ENABLE = "Enigma Unit Frames 사용";
EUF_TEXT_OPTION_FOCUS = "주시 대상";
EUF_TEXT_OPTION_FOCUS3DPORTRAIT = "주시 대상 3D 초상화 표시";
EUF_TEXT_OPTION_FOCUSCLASSICONBIG = "주시 대상 직업 아이콘 (크게)";
EUF_TEXT_OPTION_FOCUSCLASSICONSMALL = "주시 대상 직업 아이콘 (작게)";
EUF_TEXT_OPTION_FOCUSHP = "주시 대상 생명력 표시";
EUF_TEXT_OPTION_FOCUSHPPERCENT = "주시 대상 생명력 백분율 표시";
EUF_TEXT_OPTION_FOCUSPERCENTINSIDE = "주시 대상 생명력 바에 백분율 표시";
EUF_TEXT_OPTION_HEADER = "Enigma Unit Frames 옵션";
EUF_TEXT_OPTION_HELP1 = "옵션 설정을 위해 커맨드 명령을 사용합니다. 명령어 도움말:";
EUF_TEXT_OPTION_HELP2 = "/euf 변수 값 (예제: /euf PlayerHP 0)";
EUF_TEXT_OPTION_HELP3 = "상세한 변수에 대해'readme.txt'를 참고하세요. 변수 값은 0 이나 1 입니다.";
EUF_TEXT_OPTION_INVALIDPARAM = "알수없는 변수입니다.";
EUF_TEXT_OPTION_MOVINGTARGETTARGETFRAME = "대상의 대상 창 이동 (기본)";
EUF_TEXT_OPTION_NOTCOMPATIBLE = "이전의 설정이 현재 버전에 적용되지 않습니다. 당신의 설정을 초기화 하십시오.";
EUF_TEXT_OPTION_NOTINSTALLED = "옵션 설정 모듈이 설치되어 있지 않습니다. GUI 옵션을 불려올 수 없습니다.";
EUF_TEXT_OPTION_NUM = "숫자";
EUF_TEXT_OPTION_PARTY = "파티 정보";
EUF_TEXT_OPTION_PARTY3DPORTRAIT = "3D 초상화";
EUF_TEXT_OPTION_PARTYAUTOHEALTHCOLOR = "생명력에 따른 색상 변화";
EUF_TEXT_OPTION_PARTYBUFF = "파티원 버프 표시";
EUF_TEXT_OPTION_PARTYCAST = "파티원 시전 바 표시";
EUF_TEXT_OPTION_PARTYCLASS = "직업";
EUF_TEXT_OPTION_PARTYCLASSABRV = "파티 직업 생략 표시";
EUF_TEXT_OPTION_PARTYCLASSICONBIG = "직업 아이콘 (크게)";
EUF_TEXT_OPTION_PARTYCLASSICONSMALL = "직업 아이콘 (작게)";
EUF_TEXT_OPTION_PARTYCOLOR = "직업 색상으로 이름 보기";
EUF_TEXT_OPTION_PARTYHIDE = "파티원 숨기기";
EUF_TEXT_OPTION_PARTYHP = "파티원 생명력 표시";
EUF_TEXT_OPTION_PARTYLEVEL = "레벨";
EUF_TEXT_OPTION_PARTYMANAFILTER = "비-마나 직업을 위해 마나 정보 숨김";
EUF_TEXT_OPTION_PARTYMP = "파티원 마나 표시";
EUF_TEXT_OPTION_PARTYTARGET = "파티원 대상 표시";
EUF_TEXT_OPTION_PERCENT = "백분율";
EUF_TEXT_OPTION_PLAYER = "플레이어 정보";
EUF_TEXT_OPTION_PLAYER3DPORTRAIT = "3D 초상화";
EUF_TEXT_OPTION_PLAYERAUTOHEALTHCOLOR = "생명력에 따른 색상 변화";
EUF_TEXT_OPTION_PLAYERCLASSICONBIG = "직업 아이콘 (크게)";
EUF_TEXT_OPTION_PLAYERCLASSICONSMALL = "직업 아이콘 (작게)";
EUF_TEXT_OPTION_PLAYEREXTBAR = "바 확장";
EUF_TEXT_OPTION_PLAYERFRM = "정예 표시 방법";
EUF_TEXT_OPTION_PLAYERHP = "플레이어 생명력 표시";
EUF_TEXT_OPTION_PLAYERMP = "플레이어 마나 표시";
EUF_TEXT_OPTION_PLAYERPETHPMP = "플레이어 소환수 생명력/마나";
EUF_TEXT_OPTION_PLAYERPOSITION = "좌표 표시";
EUF_TEXT_OPTION_PLAYERPOSITIONAUTOHP = "인던 진입시 생명력 백분율 표시";
EUF_TEXT_OPTION_PLAYERPOSITIONTOHP = "생명력으로 변경";
EUF_TEXT_OPTION_PLAYERXP = "플레이어 경험치 표시";
EUF_TEXT_OPTION_PLAYERXPAUTO = "최대 레벨시 경험치 숨김";
EUF_TEXT_OPTION_RARE = "희귀";
EUF_TEXT_OPTION_SET = "변수 [%s]를 '%s'으로변경하였습니다.";
EUF_TEXT_OPTION_TARGET = "대상 정보";
EUF_TEXT_OPTION_TARGET3DPORTRAIT = "3D 초상화";
EUF_TEXT_OPTION_TARGETAUTOHEALTHCOLOR = "생명력에 따른 색상 변화";
EUF_TEXT_OPTION_TARGETCLASSICONBIG = "직업 아이콘 (크게)";
EUF_TEXT_OPTION_TARGETCLASSICONSMALL = "직업 아이콘 (작게)";
EUF_TEXT_OPTION_TARGETHP = "대상 생명력 표시";
EUF_TEXT_OPTION_TARGETHPPERCENT = "대상의 생명력 백분율 표시";
EUF_TEXT_OPTION_TARGETINDICATOR = "전투 수치 보기(초상화 위)";
EUF_TEXT_OPTION_TARGETINFO = "대상 정보";
EUF_TEXT_OPTION_TARGETINFOBROKENSHIELD = "방어구 가르기 표시";
EUF_TEXT_OPTION_TARGETINFOCLASS = "직업";
EUF_TEXT_OPTION_TARGETINFOELITE = "정예";
EUF_TEXT_OPTION_TARGETINFOLEVEL = "레벨";
EUF_TEXT_OPTION_TARGETINFORACE = "종족";
EUF_TEXT_OPTION_TARGETINFOTARGET = "대상의 대상 표시 (간단)";
EUF_TEXT_OPTION_TARGETMP = "대상 마나 표시";
EUF_TEXT_OPTION_TARGETMPPERCENT = "대상의 마나 백분율 표시";
EUF_TEXT_OPTION_TARGETOTWARNING = "대상의 대상 경고";
EUF_TEXT_OPTION_TARGETPERCENTINSIDE = "유닛 프레임 바에 백분율 표시";
EUF_TEXT_OPTION_TARGETTARGET = "대상의 대상 정보";
EUF_TEXT_OPTION_TARGETTARGETFRAME = "대상의 대상 (기본)";
EUF_TEXT_OPTION_TARGETTARGETHPMPBAR = "대상의 대상 생명력/마나 표시";
EUF_TEXT_OPTION_TARGETTARGETHPPERCENT = "대상의 대상 생명력 백분율 표시";
EUF_TEXT_OPTION_TARGETTARGETHPPERCENTCOLOR = "생명력에 따른 색상 변화";
EUF_TEXT_OPTION_TARGETTARGETTARGETFRAME = "대상의 대상의 대상 (기본)";
EUF_TEXT_PARTYBUFFPOSITION = "파티원 버프 위치 설정";
EUF_TEXT_PARTYCASTPOSITION = "파티원 시전 바 위치 설정";
EUF_TEXT_PARTYDEBUFFPOSITION = "파티원 디버프 위치 설정";
EUF_TEXT_PARTYTARGETPOSITION = "파티원 대상 위치 설정";
EUF_TEXT_RARE = "희귀";
EUF_TEXT_RAREELITE = "희귀+";
EUF_TEXT_RESETPOSITION = "창 위치 초기화";
EUF_TEXT_TARGET = "대상 ";
EUF_TEXT_WORLDBOSS = "우두머리";

elseif (GetLocale() == "zhTW") then

EUF_TEXT_OPTION_HEADER                        ="EUF頭像參數設定";
EUF_TEXT_OPTION_ENABLE                        ="啟用Enigma Unit Frames";
EUF_TEXT_OPTION_PLAYERFRM                     ="顯示頭像邊框";
EUF_TEXT_OPTION_PLAYERHP                      ="顯示玩家生命值";
EUF_TEXT_OPTION_PLAYERMP                      ="顯示玩家魔法值";
EUF_TEXT_OPTION_PLAYERXP                      ="顯示玩家經驗值條";
EUF_TEXT_OPTION_PLAYERXPAUTO                  ="封頂自動隱藏經驗值條";
EUF_TEXT_OPTION_PLAYERPOSITION                ="顯示玩家座標";
EUF_TEXT_OPTION_PLAYERPOSITIONTOHP            ="將座標替換為生命值百分比";
EUF_TEXT_OPTION_PLAYERPETHPMP                 ="顯示寵物的HP和MP"
EUF_TEXT_OPTION_PLAYERPOSITIONAUTOHP          ="在副本裡顯示生命值百分比";
EUF_TEXT_OPTION_PLAYERAUTOHEALTHCOLOR         ="依血量高低變化生命值條顏色";
EUF_TEXT_OPTION_PLAYEREXTBAR                  ="顯示擴展邊框";
EUF_TEXT_OPTION_PLAYERCLASSICONBIG            ="顯示玩家職業圖標(大)";
EUF_TEXT_OPTION_PLAYERCLASSICONSMALL          ="顯示玩家職業圖標(小)";
EUF_TEXT_OPTION_PLAYER3DPORTRAIT              ="顯示玩家3D頭像";

EUF_TEXT_OPTION_PARTYHP                       ="顯示隊友生命值";
EUF_TEXT_OPTION_PARTYMP                       ="顯示隊友魔法值";
EUF_TEXT_OPTION_PARTYAUTOHEALTHCOLOR          ="依血量高低變化生命值條顏色";
EUF_TEXT_OPTION_PARTYLEVEL                    ="顯示隊友級別";
EUF_TEXT_OPTION_PARTYCLASS                    ="顯示隊友職業";
EUF_TEXT_OPTION_PARTYCLASSABRV                ="以縮寫方式顯示職業";
EUF_TEXT_OPTION_PARTYCOLOR                    ="隊友名字顯示職業顏色";
EUF_TEXT_OPTION_PARTYMANAFILTER               ="無魔法的職業不顯示魔法值";
EUF_TEXT_OPTION_PARTYCLASSICONBIG             ="顯示隊友職業圖標(大)";
EUF_TEXT_OPTION_PARTYCLASSICONSMALL           ="顯示隊友職業圖標(小)";
EUF_TEXT_OPTION_PARTY3DPORTRAIT               ="顯示隊友3D頭像";
EUF_TEXT_OPTION_PARTYHIDE                     ="隱藏隊伍框架";
EUF_TEXT_OPTION_PARTYCAST                     ="顯示隊友施法條";
EUF_TEXT_OPTION_PARTYBUFF                     ="顯示隊友BUFF";
EUF_TEXT_OPTION_PARTYTARGET                   ="顯示隊友目標";

EUF_TEXT_OPTION_TARGETHP                      ="顯示目標生命值";
EUF_TEXT_OPTION_TARGETMP                      ="顯示目標魔法值";
EUF_TEXT_OPTION_TARGETHPPERCENT               ="顯示目標生命值百分比";
EUF_TEXT_OPTION_TARGETMPPERCENT               ="顯示目標魔法值百分比";
EUF_TEXT_OPTION_TARGETAUTOHEALTHCOLOR         ="依血量高低變化生命值條顏色";

EUF_TEXT_OPTION_TARGETPERCENTINSIDE           ="將百分比顯示在血條內";
EUF_TEXT_OPTION_TARGETOTWARNING               ="仇恨警報";
EUF_TEXT_OPTION_TARGETINFO                    ="顯示目標訊息";
EUF_TEXT_OPTION_TARGETINFOLEVEL               ="級別";
EUF_TEXT_OPTION_TARGETINFORACE                ="種族";
EUF_TEXT_OPTION_TARGETINFOCLASS               ="職業";
EUF_TEXT_OPTION_TARGETINFOELITE               ="精英類型";
EUF_TEXT_OPTION_TARGETINFOTARGET              ="顯示目標的目標(簡略)";
EUF_TEXT_OPTION_TARGETINFOBROKENSHIELD        ="顯示目標破甲值";
EUF_TEXT_OPTION_TARGETTARGETHPMPBAR           ="顯示目標的目標生命值/魔法值條";
EUF_TEXT_OPTION_TARGETTARGETHPPERCENT         ="顯示目標的目標生命值百分比";
EUF_TEXT_OPTION_TARGETTARGETHPPERCENTCOLOR    ="自動調整生命值百分比顏色";
EUF_TEXT_OPTION_TARGETCLASSICONBIG            ="顯示目標職業圖標(大)";
EUF_TEXT_OPTION_TARGETCLASSICONSMALL          ="顯示目標職業圖標(小)";
EUF_TEXT_OPTION_TARGETTARGETFRAME             ="顯示目標的目標(標準)";
EUF_TEXT_OPTION_TARGETTARGETTARGETFRAME       ="顯示目標的目標的目標(標準)";
EUF_TEXT_OPTION_MOVINGTARGETTARGETFRAME       ="調整目標的目標頭像位置(標準)";
EUF_TEXT_OPTION_TARGET3DPORTRAIT              ="顯示目標3D頭像";
EUF_TEXT_OPTION_TARGETINDICATOR               ="目標頭像顯示戰鬥數值";

EUF_TEXT_OPTION_FOCUSHP                       ="顯示專注目標生命值";
EUF_TEXT_OPTION_FOCUSHPPERCENT                ="顯示專注目標生命值百分比";
EUF_TEXT_OPTION_FOCUSPERCENTINSIDE            ="將百分比顯示在血條內";
EUF_TEXT_OPTION_FOCUS3DPORTRAIT               ="顯示專注目標3D頭像";
EUF_TEXT_OPTION_FOCUSCLASSICONBIG             ="顯示專注目標職業圖標(大)";
EUF_TEXT_OPTION_FOCUSCLASSICONSMALL           ="顯示專注目標職業圖標(小)";

EUF_TEXT_OPTION_NOTINSTALLED                  ="參數設定模塊未安裝,無法啟動視窗設定模式.";
EUF_TEXT_OPTION_HELP1                         ="請使用命令行模式設定,用法如下:";
EUF_TEXT_OPTION_HELP2                         ="/euf 選項 參數(示例: /euf PlayerHp 0)";
EUF_TEXT_OPTION_HELP3                         ="具體選項請參考readme.txt,參數為0/1或on/off";
EUF_TEXT_OPTION_SET                           ="已將參數[%s] 設定為 %s";
EUF_TEXT_OPTION_INVALIDPARAM                  ="無效參數";
EUF_TEXT_OPTION_NOTCOMPATIBLE                 ="以前的參數設置與新版本的參數設置不兼容,以前的參數設置將被清除,請重新設定.";

EUF_TEXT_OPTION_DISPLAYTYPE                   ="顯示方式";
EUF_TEXT_OPTION_NUM                           ="數字";
EUF_TEXT_OPTION_PERCENT                       ="百分比";
EUF_TEXT_OPTION_ELITE                         ="精英";
EUF_TEXT_OPTION_RARE                          ="稀有";
EUF_TEXT_OPTION_PLAYER                        ="玩家訊息";
EUF_TEXT_OPTION_PARTY                         ="隊伍訊息";
EUF_TEXT_OPTION_TARGET                        ="目標訊息";
EUF_TEXT_OPTION_TARGETTARGET                  ="目標的目標";
EUF_TEXT_OPTION_FOCUS                         ="專注目標";
EUF_TEXT_DEFAULTOPTIONS                       ="默認設置";
EUF_TEXT_CONFIRM                              ="確定";
EUF_TEXT_RESETPOSITION                        ="重設頭像位置";
EUF_TEXT_PARTYBUFFPOSITION                    ="調整隊友Buff位置"
EUF_TEXT_PARTYDEBUFFPOSITION                  ="調整隊友Debuff位置"
EUF_TEXT_PARTYTARGETPOSITION                  ="調整隊友目標位置"
EUF_TEXT_PARTYCASTPOSITION                    ="調整隊友施法條位置"
EUF_TEXT_TARGET                               ="目標 ";
EUF_TEXT_BROKENSHIELD                         ="破甲 ";
EUF_TEXT_LEVELTAG                             ="%s級";
EUF_TEXT_10KTAG                               ="%s萬";
EUF_TEXT_ELITE                                ="精英";
EUF_TEXT_WORLDBOSS                            ="世界精英";
EUF_TEXT_RARE                                 ="稀有";
EUF_TEXT_RAREELITE                            ="稀有精英";

EUF_FOCUSFRAME_DRAG                           ="點擊拖移框架以移動";
EUF_FOCUSFRAME_DRAG_LOCKED                    ="請先使用/focusframe unlock解除框架鎖定";


else

EUF_FOCUSFRAME_DRAG = "Click to drag"
EUF_FOCUSFRAME_DRAG_LOCKED = "Unlock command: /focusframe unlock"
EUF_TEXT_10KTAG = "%s0K"
EUF_TEXT_BROKENSHIELD = "Armor Penetration"
EUF_TEXT_CONFIRM = "Confirm"
EUF_TEXT_DEFAULTOPTIONS = "Reset Default"
EUF_TEXT_ELITE = "Elite"
EUF_TEXT_LEVELTAG = "Level %s"
EUF_TEXT_OPTION_DISPLAYTYPE = "Display Type"
EUF_TEXT_OPTION_ELITE = "Elite"
EUF_TEXT_OPTION_ENABLE = "Enable Enigma Unit Frames"
EUF_TEXT_OPTION_FOCUS = "Focus"
EUF_TEXT_OPTION_FOCUS3DPORTRAIT = "Display Focus 3D Portrait"
EUF_TEXT_OPTION_FOCUSCLASSICONBIG = "Display Class icon of Focus target (Big)"
EUF_TEXT_OPTION_FOCUSCLASSICONSMALL = "Display Class icon of Focus target (Small)"
EUF_TEXT_OPTION_FOCUSHP = "Display HP Value of Focus target"
EUF_TEXT_OPTION_FOCUSHPPERCENT = "Display HP Percent of Focus target"
EUF_TEXT_OPTION_FOCUSPERCENTINSIDE = "Display percent inside health bar"
EUF_TEXT_OPTION_HEADER = "Enigma Unit Frames"
EUF_TEXT_OPTION_HELP1 = "EUF command:"
EUF_TEXT_OPTION_HELP2 = "/euf option argument (example: /euf PlayerHp 0)"
EUF_TEXT_OPTION_HELP3 = "Argument: 0/1 or off/on"
EUF_TEXT_OPTION_INVALIDPARAM = "Invalid Argument"
EUF_TEXT_OPTION_MOVINGTARGETTARGETFRAME = "Movable Target's Target Frame"
EUF_TEXT_OPTION_NOTCOMPATIBLE = "EUF's setting is NOT compatible to old version"
EUF_TEXT_OPTION_NOTINSTALLED = "GUI module is not installed."
EUF_TEXT_OPTION_NUM = "Number"
EUF_TEXT_OPTION_PARTY = "PARTY"
EUF_TEXT_OPTION_PARTY3DPORTRAIT = "Display Party's 3D Portrait"
EUF_TEXT_OPTION_PARTYAUTOHEALTHCOLOR = "color of health bar with HP percent"
EUF_TEXT_OPTION_PARTYBUFF = "Party's Buff"
EUF_TEXT_OPTION_PARTYCAST = "Party's Cast bars"
EUF_TEXT_OPTION_PARTYCLASS = "Party's class"
EUF_TEXT_OPTION_PARTYCLASSABRV = "Reduce Class text"
EUF_TEXT_OPTION_PARTYCLASSICONBIG = "Party's class icon (Big)"
EUF_TEXT_OPTION_PARTYCLASSICONSMALL = "Party's class icon (Small)"
EUF_TEXT_OPTION_PARTYCOLOR = "Party members' name with class color"
EUF_TEXT_OPTION_PARTYHIDE = "Hide Party Frame"
EUF_TEXT_OPTION_PARTYHP = "Party's HP value"
EUF_TEXT_OPTION_PARTYLEVEL = "Party's level"
EUF_TEXT_OPTION_PARTYMANAFILTER = "Do NOT mana when member is not using mana system"
EUF_TEXT_OPTION_PARTYMP = "Party's MP value"
EUF_TEXT_OPTION_PARTYTARGET = "Party's target frame"
EUF_TEXT_OPTION_PERCENT = "Percent"
EUF_TEXT_OPTION_PLAYER = "PLAYER"
EUF_TEXT_OPTION_PLAYER3DPORTRAIT = "Player's 3D Portrait"
EUF_TEXT_OPTION_PLAYERAUTOHEALTHCOLOR = "color of health bar with HP percent"
EUF_TEXT_OPTION_PLAYERCLASSICONBIG = "Player's class icon (Big)"
EUF_TEXT_OPTION_PLAYERCLASSICONSMALL = "Player's class icon (Small)"
EUF_TEXT_OPTION_PLAYEREXTBAR = "extend frame"
EUF_TEXT_OPTION_PLAYERFRM = "dragon frame"
EUF_TEXT_OPTION_PLAYERHP = "Player's HP value"
EUF_TEXT_OPTION_PLAYERMP = "Player's MP value"
EUF_TEXT_OPTION_PLAYERPETHPMP = "Pet's HP and MP value"
EUF_TEXT_OPTION_PLAYERPOSITION = "Player's Coordinate"
EUF_TEXT_OPTION_PLAYERPOSITIONAUTOHP = "health percent when player is inside a dungeon"
EUF_TEXT_OPTION_PLAYERPOSITIONTOHP = "Display HP percent instead of Coordinate"
EUF_TEXT_OPTION_PLAYERXP = "EXP bar"
EUF_TEXT_OPTION_PLAYERXPAUTO = "Hide EXP bar when player reach max level"
EUF_TEXT_OPTION_RARE = "Rare"
EUF_TEXT_OPTION_SET = "Option [%s] is set to %s"
EUF_TEXT_OPTION_TARGET = "TARGET"
EUF_TEXT_OPTION_TARGET3DPORTRAIT = "Target's 3D Portrait"
EUF_TEXT_OPTION_TARGETAUTOHEALTHCOLOR = "color of health bar with HP percent"
EUF_TEXT_OPTION_TARGETCLASSICONBIG = "Target's class icon (Big)"
EUF_TEXT_OPTION_TARGETCLASSICONSMALL = "Target's class icon (Small)"
EUF_TEXT_OPTION_TARGETHP = "Target's HP value"
EUF_TEXT_OPTION_TARGETHPPERCENT = "Target's HP percent"
EUF_TEXT_OPTION_TARGETINDICATOR = "Target's battle indicator"
EUF_TEXT_OPTION_TARGETINFO = "Target information"
EUF_TEXT_OPTION_TARGETINFOBROKENSHIELD = "Target's Armor Penetration"
EUF_TEXT_OPTION_TARGETINFOCLASS = "Class"
EUF_TEXT_OPTION_TARGETINFOELITE = "Elite"
EUF_TEXT_OPTION_TARGETINFOLEVEL = "Level"
EUF_TEXT_OPTION_TARGETINFORACE = "Race"
EUF_TEXT_OPTION_TARGETINFOTARGET = "simple Target's target frame"
EUF_TEXT_OPTION_TARGETMP = "Target's MP value"
EUF_TEXT_OPTION_TARGETMPPERCENT = "Target's MP percent"
EUF_TEXT_OPTION_TARGETOTWARNING = "Aggro warning"
EUF_TEXT_OPTION_TARGETPERCENTINSIDE = "Display percent inside health bar"
EUF_TEXT_OPTION_TARGETTARGET = "Target's target"
EUF_TEXT_OPTION_TARGETTARGETFRAME = "Target's target frame (Standard)"
EUF_TEXT_OPTION_TARGETTARGETHPMPBAR = "Target of target's HP/MP bar"
EUF_TEXT_OPTION_TARGETTARGETHPPERCENT = "Target of target's HP percent"
EUF_TEXT_OPTION_TARGETTARGETHPPERCENTCOLOR = "color of health bar with HP percent"
EUF_TEXT_OPTION_TARGETTARGETTARGETFRAME = "Target of target's target"
EUF_TEXT_PARTYBUFFPOSITION = "Adjust party's buff position"
EUF_TEXT_PARTYCASTPOSITION = "Adjust Party's cast bar position"
EUF_TEXT_PARTYDEBUFFPOSITION = "Adjust Party's debuff position"
EUF_TEXT_PARTYTARGETPOSITION = "Adjust Party's target position"
EUF_TEXT_RARE = "Rare"
EUF_TEXT_RAREELITE = "Rare elite"
EUF_TEXT_RESETPOSITION = "Reset frame position"
EUF_TEXT_TARGET = "TARGET"
EUF_TEXT_WORLDBOSS = "World Boss"

end;
