--由 一区 烈焰峰 - 水镜花缘 汉化

local L local L = LibStub("AceLocale-3.0"):NewLocale("Gladius", "zhCN", false)

if L then

	--Welcome message
	L["Welcome to Gladius!"] = "欢迎使用 Gladius!"
	L["First run has been detected, displaying test frame."] = "第一次使用,显示测试框体"
	L["Valid slash commands are:"] = "命令设置为:"
	L["/gladius ui"] = "/gladius ui"
	L["/gladius test1-5"] = "/gladius test1-5"
	L["If this is not your first run please lock or move the frame to prevent this from happening."] = "如果非初次使用，请锁定或者移动框体以保证不显示该信息."

	--Frame
	L["Gladius - drag to move"] = "Gladius - 按住拖动"

	--Options
	L["General"] = "一般"
	L["General settings"] = "一般设置"	
	L["Bars"] = "条"
	L["Bar settings"] = "条设置"
	L["Colors"] = "颜色和纹理"
	L["Color settings"] = "颜色纹理设置"
	L["Size and margin"] = "大小和边缘"
	L["Size and margin settings"] = "大小和边缘设置"
	L["Text"] = "文字"
	L["TextDesc"] = "文字设置"
	L["Lock frame"] = "锁定界面"
	L["Frame resize"] = "界面重置"
	L["If this is enabled the frame will automaticly get resized to the appropriate size every time you enter an arena"] = "按人数自动调整大小"
	L["Toggle if the frame can be moved"] = "点击后锁定"
	L["Frame scale"] = "界面大小"
	L["Scale of the frame"] = "界面大小"
	L["Frame padding"] = "界面填充颜色"
	L["Padding of the frame"] = "界面填充颜色"
	L["Show cast bars"] = "显示施法条"
	L["Show power percentage"] = "显示能力条百分比"
	L["Show mana/energy/rage percentage on the power bar"] = "显示魔法/能量/怒气百分比"
	L["Show race text"] = "显示种族文本"
	L["Show race text on the power bar"] = "在能力条上显示种族文本"
	L["Show class text"] = "显示职业文本"
	L["Show class text on the power bar"] = "在能力条上显示职业文本"
	L["Highlight target"] = "目标突出"
	L["Toggle if the selected target should be highlighted"] = "目标突出显示"
	L["Show border around target"] = "目标边框"
	L["Toggle if a border should be shown around the selected target"] = "目标边框显示"
	L["Bar texture"] = "条纹理"
	L["Bar width"] = "条宽"
	L["Width of the health and power bars"] = "血条和能力条的宽度"
	L["Health bar height"] = "血条高度"
	L["Height of the health bars"] = "血条高度"
	L["Power bar height"] = "能力条高度"
	L["Height of the power bars"] = "能力条高度"
	L["Cast bar height"] = "施法条高度"
	L["Height of the cast bars"] = "施法条高度"
	L["Bar bottom margin"] = "条间隙"
	L["Margin to the next bar"] = "条之间的间隙"
	L["Frame color"] = "界面颜色"
	L["Color of the frame"] = "界面颜色"
	L["Selected border color"] = "选择边框颜色"
	L["Color of the selected targets border"] = "选择目标边框颜色"
	L["Mana color"] = "魔法"
	L["Color of the mana bar"] = "蓝条的颜色"
	L["Energy color"] = "能量"
	L["Color of the energy bar"] = "能量条颜色"
	L["Rage color"] = "怒气"
	L["Color of the rage bar"] = "怒气条颜色"
	L["Runic Power color"] = "符文"
	L["Color of the runic power bar"] = "符文条颜色"
	L["Game default"] = "游戏默认"
	L["Use game default rage color"] = "使用游戏默认的怒气条颜色"
	L["Use game default energy color"] = "使用游戏默认的能量条颜色"
	L["Use game default mana color"] = "使用游戏默认的魔法条颜色"
	L["Use game default runic power color"] = "使用游戏默认的符文条颜色"
	L["Cast bar color"] = "施法条颜色"
	L["Color of the cast bar"] = "施法条颜色"
	L["Health text size"] = "血量文字大小"
	L["Size of the health bar text"] = "血量文字大小"
	L["Health text color"] = "血量文字颜色"
	L["Color of the health bar text"] = "血量文字颜色"
	L["Mana text size"] = "魔法文字大小"
	L["Size of the mana bar text"] = "魔法文字大小"
	L["Mana text color"] = "魔法文字颜色"
	L["Color of the mana bar text"] = "魔法文字颜色"
	L["Cast bar text size"] = "施法条文字大小"
	L["Size of the cast bar text"] = "施法条文字大小"
	L["Cast bar text color"] = "施法条文字颜色"
	L["Color of the cast bar text"] = "施法条文字颜色"
	L["Aura text size"] = "光环文字大小"
	L["Size of the aura text"] = "光环文字大小"
	L["Aura text color"] = "光环文字颜色"
	L["Color of the aura text"] = "光环文字颜色"
	L["Show power bars"] = "显示能力条"
	L["Show class icon"] = "显示职业图标"
	L["Show class icon\nIMPORTANT:\nToggling this off will disable showing auras even if it is enabled"] = "显示职业图标\n注意:\n开启此功能显示光环功能才可用"
	L["Show auras"] = "显示光环"
	L["Show important auras over the class icon with a timer. You can select which auras to show and their respective priorites in the auralist.lua file"] = "重要的光环效果会覆盖职业图标并记时。你可以在auralist.lua中更改技能和优先级"
	L["Left Click"] = "左键"
	L["Right Click"] = "右键"
	L["Middle Mouse Click"] = "中键"
	L["Mouse 4 Click"] = "鼠标按键4"
	L["Mouse 5 Click"] = "鼠标按键5"
	L["Spell Name"] = "法术名称"
	L["Cast Spell"] = "释放法术"
	L["Show the actual power"] = "显示数值"
	L["Show the actual mana/energy/rage on the power bar"] = "显示魔法/能量/怒气的数值"
	L["Show max power"] = "显示最大值"
	L["Show maximum mana/energy/rage on the power bar"] = "显示魔法/怒气/能量的最大值"
	L["Show power text"] = "显示文字"
	L["Show mana/energy/rage text on the power bar"] = "显示魔法/怒气/能量的文本文字"
	L["Show target icon"] = "显示目标图标"
	L["Trinket"] = "显示徽章状态"
	L["TrinketDesc"] = "在敌人名右侧显示徽章状态"
	L["Sizes"] = "大小"
	L["SizesDesc"] = "文字大小"
	L["Target icon size"] = "目标图标大小"
	L["TargetIconSizeDesc"] = "目标图标大小"
	L["Big icon scale"] = "大图标"
	L["BigIconScaleDesc"] = "大饰品图标"
	
	L["TrinketDisplay"] = "徽章显示"
	L["TrinketDisplayDesc"] = "选择如何显示徽章"
	L["trinketNameText"] = "文字"
	L["trinketNameIcon"] = "图标"
	L["trinketBigIcon"] = "大图标"
	L["trinketOverrideIcon"] = "覆盖职业/光环图标"
	L["trinketSmallIcon"] = "小图标"
	L["trinketGridIcon"] = "Grid-样式图标"
	
	L["enemyAnnounce"] = "新的敌人"
	L["enemyAnnounceDesc"] = "通告找到的新敌人"
	L["trinketUsedAnnounce"] = "徽章使用"
	L["trinketUsedAnnounceDesc"] = "通告敌人使用徽章"
	L["trinketUpAnnounce"] = "徽章冷却"
	L["trinketUpAnnounceDesc"] = "通告敌人徽章冷却完毕"
	
	L["announceType"] = "通告类型"
	L["announceTypeDesc"] = "通告到哪个频道"
	
	L["announceParty"] = "小队"
	L["announceRw"] = "团队警报"
	L["announceSct"] = "SCT"
	L["announceMsbt"] = "MSBT"
	L["announceFct"] = "FCT (Blizzard)"
	
	L["lowHealthAnnounce"] = "生命垂危通告"
	L["lowHealthAnnounceDesc"] = "通告敌人生命垂危."
	L["lowHealthPercentage"] = "生命垂危阀值"
	L["lowHealthPercentageDesc"] = "低于这个值将会被判定为生命垂危"
	
	L["Grow frame upwards"] = "向上增长"
	L["If this is toggled the frame will grow upwards instead of downwards."] = "勾选此项,条将会向上增长"
	
	L["Announcements"] = "通告设置"
	L["Set options for different announcements"] ="设置不同的通告"
	L["Trinket display"] = "徽章显示"
	L["Set options for the trinket status display"] = "设置徽章显示方法"
	L["Clicks"] = "点击"
	L["Set options for mouse clicks on the arena targets"] = "设置各种鼠标点击敌人的功能"
	L["focus"] = "焦点"
	
--font
	L["GFont"] = "Fonts\\ZYKai_C.TTF"
	
--Announcement
	L["LowHP"] = "生命垂危 %s"
	L["trinketready"] = "徽章冷却完毕: %s (%s)"
	L["trinketused"] = "徽章已经使用: %s (%s)"
	L["Gtestplayer"] = "敌方玩家"
	
	BINDING_HEADER_GLADIUS 				= "Gladius"
	BINDING_NAME_GLADIUSTARGET1_LEFT 	= "Left click enemy #1"
	BINDING_NAME_GLADIUSTARGET2_LEFT 	= "Left click enemy #2"
	BINDING_NAME_GLADIUSTARGET3_LEFT 	= "Left click enemy #3"
	BINDING_NAME_GLADIUSTARGET4_LEFT 	= "Left click enemy #4"
	BINDING_NAME_GLADIUSTARGET5_LEFT 	= "Left click enemy #5"
	BINDING_NAME_GLADIUSTARGET1_RIGHT 	= "Right click enemy #1"
	BINDING_NAME_GLADIUSTARGET2_RIGHT 	= "Right click enemy #2"
	BINDING_NAME_GLADIUSTARGET3_RIGHT 	= "Right click enemy #3"
	BINDING_NAME_GLADIUSTARGET4_RIGHT	= "Right click enemy #4"
	BINDING_NAME_GLADIUSTARGET5_RIGHT 	= "Right click enemy #5"
		
end
