-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/gather-hud/localization/

-- zhCN Localization file, from NightOwl
local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("GatherHud", "zhCN")
if not L then return end

L["A depth effect that controls how much the size of the icons changes for nodes in the near and far distance"] = "这效果能用大小显示远近图示的差异"
L["Angle of view"] = "视角"
L["Displays a circle border representing the drawing area of the hud"] = "显示显示器圆圈的边框来展示显示器的绘画范围"
L["Displays a letter N on the border of the hud circle to indicate the North direction"] = "在显示器圆圈的边框用N字来指示北面"
L["Do not allow the GatherHud camera pitch to go below this angle"] = "禁止GatherHud镜头的倾斜度少于这角度"
L["Enable GatherHud"] = "启用Gatherhud"
L["Enable or disable GatherHud"] = "启动/关闭抬头显示器"
-- L["gatherhud"] = "gatherhud"
-- L["GatherHud"] = "GatherHud"
L["GATHERHUD_DESC"] = [=[GatherHud 是一个调校自由度很高的抬头显示器可让你很快地看见附近的资源点. GatherHud 可支持 Routes.

你可将鼠标放在滚动条条上用滚动条滚轮作1格的调校.]=]
L["GatherHud Icon Options"] = "显示器图标选项"
L["GatherHud Options"] = "GatherHud选项"
L["GatherHud Routes Support"] = "Routes支援"
L["Hud Alpha"] = "显示器透视度"
L["Hud map radius"] = "显示器地图半径"
L["Hud Width"] = "显示器宽度"
L["Hud X-Position"] = "显示器 X-偏移位置"
L["Hud Y-Position"] = "显示器 Y-偏移位置"
L["Icon alpha"] = "图示的透视度"
L["Icon depth effect"] = "图示的深度"
L["Icon size"] = "图示大小"
L["Keybind to toggle GatherHud"] = "设定开关的热键"
L["Minimum Pitch"] = "最小倾斜度"
L["Self color"] = "自身的颜色"
L["Show Hud circle"] = "显示显示器的圆圈"
L["Show North indicator"] = "显示向北指示"
L["Show Routes in the hud"] = "在显示器显示Routes"
L["The alpha transparency of the hud"] = "显示器透明度"
L["The alpha transparency of the icons"] = "图示的透明度"
L["The angle of elevation from the horizontal plane to view the hud at"] = "将视角从平面作角度提升"
L["The color of the small circle that represents yourself in the center of the hud"] = "显示器中间代表你的小圆圈的颜色"
L["The pixel width of the hud. In effect, this controls the scaling of the entire hud"] = "显示器像素宽度. 这决定整个显示器的比例"
L["The radius in yards the hud will draw nodes for from your position"] = "从你现时位置让显示器绘画资源点的半径的码数"
L["The size of the icons displayed in the hud"] = "显示器图示的大小"
L["The X offset coordinate of the hud from the center of the screen"] = "由屏幕中心起的显示器 X-偏移坐标"
L["The Y offset coordinate of the hud from the center of the screen"] = "由屏幕中心起的显示器 X-偏移坐标"
-- L["Use Character Pitch"] = "Use Character Pitch"
L["Use Minimum Pitch"] = "使用最小倾斜度"
-- L["Use the Character pitch instead of a user-specified angle"] = "Use the Character pitch instead of a user-specified angle"

L["Gather HUD: "] = "采集助手 HUD: ";
L["Enabled"] = "启用";
L["Disabled"] = "禁用";
