local L = LibStub("AceLocale-3.0"):NewLocale("DuowanMove", "enUS", true)

L["MainBarText"] = "Main Bar";
L["BottomLeftBarText"] = "Bottom Left Bar";
L["BottomRightBarText"] = "Bottom Right Bar";
L["RightBar1Text"] = "Right Bar";
L["RightBar2Text"] = "Left Bar";
L["ShapeShiftBarText"] = "Shapshift Bar";
L["ExtraBar1Text"] = "Extra Bar 1";
L["ExtraBar2Text"] = "Extra Bar 2";
L["ExtraBar3Text"] = "Extra Bar 3";
L["ExtraBar4Text"] = "Extra Bar 4";
L["ExtraBar5Text"] = "Extra Bar 5";
L["PlayerPetBarText"] = "Pet Bar";
L["MultiCastBarText"] = "MultiCastBar";
L["PossessBarText"] = "PossessBarText";	
L["BagBarText"] = "Bag Bar";
L["MenuBarText"] = "Menu Bar";
L["UnitPlayerFrameText"] = "Player Frame";
L["UnitTargetFrameText"] = "Target Frame";
L["UnitPartyFrameText"] = "Party Frame";
L["UnitFocusFrameText"] = "Focus Frame";
L["CastBarFrameText"] = "Casting Bar";
L["MirrorTimerFrameText"] = "Mirror Timer";
L["ExBarText"] = "ExBar";
L["MiniMapFrameText"] = "MiniMap";
L["DurabilityFrameText"] = "Durability Frame";
L["BuffFrameText"] = "Buff Frame";
	L["ACTIONBAR"] = "动作条";
	L["UNITFRAME"] = "头像框架";
	L["CASTBAR"] = "施法经验条";
	L["OTHER"] = "其他";
	L["TEXTURE"] = "贴图";

	L["基本选项"] = "基本选项";
	L["锁定模块"] = "锁定位置";
	L["锁定模块的位置"] = "锁定模块的位置";
	L["解锁模块"] = "解锁模块";
	L["解锁模块位置"] = "解锁模块位置";
	L["隐藏模块"] = "隐藏模块";
	L["隐藏模块"] = "隐藏模块";
	L["隐藏选中的模块"] = "隐藏选中的模块";
	L["绑定按键"] = "绑定按键";
	L["为该动作条绑定按键"] = "为该动作条绑定按键";
	L["排列方式"] = "排列方式";
	L["竖向排列"] = "竖向排列";
	L["按照垂直方向排列"] = "按照垂直方向排列";
	L["横向排列"] = "横向排列";
	L["按照水平方向排列"] = "按照水平方向排列";
	L["双行排列"] = "双行排列";
	L["排列为两行"] = "排列为两行";
	L["趣味排列"] = "趣味排列";
	L["非同寻常的排列方式"] = "非同寻常的排列方式";
	L["按键操作"] = "按键操作";
	L["增加按键"] = "增加按键";
	L["增加动作条的按键数量"] = "增加动作条的按键数量";
	L["减少按键"] = "减少按键";
	L["减少动作条的按键数量"] = "减少动作条的按键数量";
	L["关闭"] = "关闭";
	L["关闭菜单"] = "关闭菜单";
	L["改变长度"] = "改变长度";
	L["设置经验条的长度比例"] = "设置经验条的长度比例";
	L["缩放比例"] = "缩放比例";
	L["设置模块的比例"] = "设置模块的比例";
	L["其他操作"] = "其他操作";
	L["按键间距"] = "按键间距";
	L["设置按键之间的间距"] = "设置按键之间的间距";
	L["最小化模块"] = "最小化模块";
	L["最小化模块到只剩标题头"] = "最小化模块到只剩标题头";
	L["恢复模块"] = "恢复模块";
	L["恢复模块到原来的外观"] = "恢复模块到原来的外观";
	L["多玩移动"] = "多玩移动";
	L["解锁模块"] = "解锁模块";
	L["隐藏所有元素的标题头"] = "隐藏所有元素的标题头";
	L["隐藏元素的标题头和背景\n使其不可移动"] = "隐藏元素的标题头和背景\n使其不可移动";
	L["隐藏模块"] = "隐藏模块";
	L["方案管理"]  ="方案管理";
	L["介绍"] = "<方案>是多玩或者玩家自己预设的配置, 通过方案管理, 你可以在已经存在的方案基础上开发自己的界面. 如果喜欢, 你甚至可以将你自己的方案与别的玩家分享. ";
	L["选择方案"] = "选择方案";
	L["选择一套预设方案"] = "选择一套预设方案";
	L["恢复缺省"] = "恢复缺省";
	L["恢复到缺省方案"] = "恢复到多玩预定义的缺省方案";
	L["新建方案"] = "新建方案";
	L["新建一套方案"] = "新建一套方案";
	L["删除方案"] = "删除方案";
	L["删除选中的方案"] = "删除选中的方案";
	L["你缺省删除当前选中方案吗?"] = "你缺省删除当前选中方案吗?";
	L["打开配置"] = "打开配置";
	L["右键打开菜单"] = "右键打开菜单";

	for i = 1, 5 do
		_G["BINDING_HEADER_DWEXTERBAR" .. i] = format("額外動作條%d", i);
		for b = 1, 12 do
			_G["BINDING_NAME_CLICK dwExtraBar".. i .. "Button" .. b .. ":LeftButton"] =  format("動作鍵%d", b);
		end
	end

