--[[
Battlegrounds.en.lua
This series of files defines the loot buttons in the Atlas interface
for the battleground maps.  There is a need for multiple versions of the
file due to slight translation differences between Atlas languages.

The English file also contains the loot tables for the battleground loot tables.
]]
------------
-- Layout --
------------
AtlasLootBattlegrounds = {

    AlteracValleyNorth = {
        "AlteracFactions";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "AVMisc";
        "AVBlue";
        "AVPurple";
        };
    
    AlteracValleySouth = {
        "AlteracFactions";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "AVMisc";
        "AVBlue";
        "AVPurple";
    };
    
    ArathiBasin = {
        "MiscFactions";
        "MiscFactions";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "";
        "ABMisc";
        "AB20291";
        "AB20292";
        "AB3039";
        "AB40491";
        "AB40492";
        "AB5059";
        "AB60";
        "";
        "ABSets1";
    };
    
    WarsongGulch = {
        "";
        "";
        "";
        "";
        "";
        "WSGMisc";
        "WSG1019";
        "WSG2029";
        "WSG3039";
        "WSG4049";
        "WSG5059";
        "WSG60";
    };
};
