if ( GetLocale() == "zhTW" ) then 
	FRIENDS_MENU_XP_LOADED = "FriendsMenuXP加載成功, 作者Warbaby."
	FRIENDS_MENU_XP_CANNOT_TARGET = "FriendsMenuXP無法選定<$name$>為目標。"

	FMXP_BUTTON_ADD_FRIEND = "加為好友"
	FMXP_BUTTON_SEND_WHO = "查詢詳情"
	FMXP_BUTTON_ADD_GUILD = "邀請入會"
	FMXP_BUTTON_GET_NAME = "複製名字"
	FMXP_BUTTON_TRADE = "交易"
	FMXP_BUTTON_GUILD_LEAVE = "退出工會！"
	FMXP_BUTTON_GUILD_PROMOTE = "提升該會員"
	FMXP_BUTTON_PVP_REPORT_AFK = "舉報混子"
	FMXP_BUTTON_SET_FOCUS = "設為專注目標"
	TMXP_BUTTON_CLEAR_FOCUS = "取消專注目標";
	FMXP_BUTTON_PROMOTE = "提升為隊長"
	FMXP_BUTTON_LOOT_PROMOTE = "設為拾取者"
	FMXP_BUTTON_ACHIEVEMENTS = "對比成就"

	FMXP_SPELL_MAGE_INTELLECT = "秘法智力"
	FMXP_SPELL_MAGE_INTELLECT_X = "秘法光輝"

	FMXP_SPELL_PRIEST_FORTITUDE = "真言術:韌"
	FMXP_SPELL_PRIEST_FORTITUDE_X = "堅韌禱言"
	FMXP_SPELL_PRIEST_SPIRIT = "神聖之靈"
	FMXP_SPELL_PRIEST_SPIRIT_X = "精神禱言"
	FMXP_SPELL_PRIEST_SHADOW = "暗影防護"
	FMXP_SPELL_PRIEST_SHADOW_X = "暗影防護禱言"

	FMXP_SPELL_DRUID_MILD = "野性印記"
	FMXP_SPELL_DRUID_MILD_X = "野性賜福"

	FMXP_SPELL_PAL_WISDOM	= "智慧祝福"
	FMXP_SPELL_PAL_WISDOM_X	= "強效智慧祝福"
	FMXP_SPELL_PAL_MIGHT	= "力量祝福"
	FMXP_SPELL_PAL_MIGHT_X	= "強效力量祝福"
	FMXP_SPELL_PAL_SALV 	= "拯救祝福"
	FMXP_SPELL_PAL_SALV_X 	= "强效拯救祝福"
	FMXP_SPELL_PAL_LIGHT	= "光明祝福"
	FMXP_SPELL_PAL_LIGHT_X	= "强效光明祝福"
	FMXP_SPELL_PAL_KINGS	= "王者祝福"
	FMXP_SPELL_PAL_KINGS_X	= "強效王者祝福"
	FMXP_SPELL_PAL_SANCT	= "庇護祝福"
	FMXP_SPELL_PAL_SANCT_X	= "強效庇護祝福"

	FMXP_SPELL_WL_SUMMON = "召喚儀式"
end