FRIENDS_MENU_XP_LOADED = "FriendsMenuXP加载成功, 作者Warbaby-二区暗影之月<凌翼>."
FRIENDS_MENU_XP_CANNOT_TARGET = "FriendsMenuXP无法选定<$name$>为目标。"

FMXP_BUTTON_REPORT_STAT = "发送属性"
FMXP_BUTTON_ADD_FRIEND = "加为好友"
FMXP_BUTTON_SEND_WHO = "查询详情"
FMXP_BUTTON_ADD_GUILD = "工会邀请"
FMXP_BUTTON_GET_NAME = "复制名字"
FMXP_BUTTON_TRADE = "交易"
FMXP_BUTTON_GUILD_LEAVE = "退出公会！"
FMXP_BUTTON_GUILD_PROMOTE = "提升该会员"
FMXP_BUTTON_PVP_REPORT_AFK = "举报混子"
FMXP_BUTTON_SET_FOCUS = "设为焦点"
TMXP_BUTTON_CLEAR_FOCUS = "清除焦点"

FMXP_SPELL_MAGE_INTELLECT = "奥术智慧"
FMXP_SPELL_MAGE_INTELLECT_X = "奥术光辉"

FMXP_SPELL_PRIEST_FORTITUDE = "真言术：韧"
FMXP_SPELL_PRIEST_FORTITUDE_X = "坚韧祷言"
FMXP_SPELL_PRIEST_SPIRIT = "神圣之灵"
FMXP_SPELL_PRIEST_SPIRIT_X = "神圣祷言"
FMXP_SPELL_PRIEST_SHADOW = "防护暗影"
FMXP_SPELL_PRIEST_SHADOW_X = "暗影防护祷言"

FMXP_SPELL_DRUID_MILD = "野性印记"
FMXP_SPELL_DRUID_MILD_X = "野性赐福"

FMXP_SPELL_PAL_WISDOM	= "智慧祝福"
FMXP_SPELL_PAL_WISDOM_X	= "强效智慧祝福"
FMXP_SPELL_PAL_MIGHT	= "力量祝福"
FMXP_SPELL_PAL_MIGHT_X	= "强效力量祝福"
FMXP_SPELL_PAL_SALV 	= "拯救祝福"
FMXP_SPELL_PAL_SALV_X 	= "强效拯救祝福"
FMXP_SPELL_PAL_LIGHT	= "光明祝福"
FMXP_SPELL_PAL_LIGHT_X	= "强效光明祝福"
FMXP_SPELL_PAL_KINGS	= "王者祝福"
FMXP_SPELL_PAL_KINGS_X	= "强效王者祝福"
FMXP_SPELL_PAL_SANCT	= "庇护祝福"
FMXP_SPELL_PAL_SANCT_X	= "强效庇护祝福"

FMXP_SPELL_WL_SUMMON = "召唤仪式"

--[[
SPELL_MAGE_INTELLECT
SPELL_PRIEST_FORTITUDE
SPELL_PRIEST_SPIRIT
SPELL_PRIEST_SHADOW
SPELL_DRUID_MILD
SPELL_WL_SUMMON
SPELL_PAL_WISDOM
SPELL_PAL_MIGHT
SPELL_PAL_SALV
SPELL_PAL_LIGHT
SPELL_PAL_KINGS
SPELL_PAL_SANCT
]]